# Generated by Django 4.0.1 on 2022-01-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glucose',
            old_name='name',
            new_name='device',
        ),
    ]
